fix: remove non ASCII characters
IBM/zDNN pull request #12
Opened 2022-07-22 22:36 UTC by dev-japo

### Description
Remove non ASCII characters. See `man ascii`for more information.

#### Fixes
- remove non ASCII characters with focus on disclaimer and comments and licenses
- call: `find . -type f -exec sed -i 's/[\xC2\xA0]//g' {} \;`

Signed-off-by: Jan Polensky <jan.polensky@ibm.com>

2022-07-25 13:44 UTC, n-marion requested changes
I do not think this PR is necessary for two reasons

- Every example of the Copyright / License has the URL indented. 
- Multi-line comments have the expected C format. Removing the indentation will cause our formatters to reset them.

2022-07-25 14:35 UTC, dev-japo commented
r

> I do not think this PR is necessary for two reasons
> 
> * Every example of the Copyright / License has the URL indented.
> * Multi-line comments have the expected C format. Removing the indentation will cause our formatters to reset them.

Hi @n-marion,

saw your comment and fixed the PR to the expectation.

2022-07-25 16:58 UTC, n-marion approved these changes

2022-07-26 11:31 UTC, Andreas-Krebbel approved these changes

2022-07-26 16:15 UTC, merged